version: 2
jobs:
  build:
    machine: true
    environment:
      BASE_VERSION: 0.1
      TAG: ${CIRCLE_PROJECT_USERNAME}_${CIRCLE_PROJECT_REPONAME}_${BASE_VERSION}.${CIRCLE_BUILD_NUM}.simg
      IMAGE_FILE: ${CIRCLE_PROJECT_USERNAME}_${CIRCLE_PROJECT_REPONAME}_${TAG}.simg
    steps:
      - checkout
      - run: 
          name: Check if Singularity recipe exists
          command: test -f Singularity
      - run:
          name: Set-up singularity and sregistry
          command: |
            chmod u+x *.sh
            /bin/bash setup.sh
      - run:
          name: Test Singularity
          command: |
              singularity selftest
      - run:
          name: Build image from Singularity recipe
          command: |
              sudo singularity build ${IMAGE_FILE} Singularity
              test -f $IMAGE_FILE
      - run:
          name: Test the image... Marco!"
          command: |
              singularity exec $IMAGE_FILE echo "Polo!"
      - run:
          name: Deploy the image
          command: |
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME
              cp Singularity Singularity.${BASE_VERSION}.${CIRCLE_BUILD_NUM}
              git commit -m "Deploy ${BASE_VERSION}.${CIRCLE_BUILD_NUM}"
              git push 
      
