defaults: &defaults
  machine: true
  working_directory: /tmp
  environment:
    BASE_VERSION: 0.1


version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Check if Singularity recipe exists
          command: test -f Singularity
      - run:
          name: Set-up singularity and sregistry
          command: |
            chmod u+x *.sh
            /bin/bash setup.sh
      - run:
          name: Test Singularity
          command: |
              singularity selftest
      - run:
          name: Build image from Singularity recipe
          command: |
              sudo singularity build container.simg Singularity
              test -f container.simg
      - persist_to_workspace:
          root: /tmp
          paths:
            - container.simg
            - Singularity



  test:
    <<: *defaults
    steps:    
      - attach_workspace:
        at: /tmp
      - run:
          name: Test the image... Marco!"
          command: |
              singularity exec /tmp/container.simg echo "Polo!"
              
              
    
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
        requires:
          - build
              
              
#this is inf loop, need to push to branch that circleci is not watching..
#      - run: 
#          name: Deploy the image
#          command: |
#              git config --global user.email $GH_EMAIL
#              git config --global user.name $GH_NAME
#              cp Singularity Singularity.${BASE_VERSION}.${CIRCLE_BUILD_NUM}
#              git add Singularity.${BASE_VERSION}.${CIRCLE_BUILD_NUM}
#              git commit -m "Deploy ${BASE_VERSION}.${CIRCLE_BUILD_NUM}"
#              git push 
#
#              export IMAGE_FILE=${CIRCLE_PROJECT_USERNAME}_${CIRCLE_PROJECT_REPONAME}_${BASE_VERSION}.${CIRCLE_BUILD_NUM}.simg
