version: 2
jobs:
  build:
    machine: true
    environment:
      ORG: khanlab
      NAME: prepdwi
      VERSION: 0.1
    steps:
      - checkout
      - run:
          name: Set-up singularity
          command: |
            setup.sh
      - run:
          name: Checking singularity build
          command: |
              singularity selfttest
      
